### ISSUE TITLE
Great Job, are there any updates in the pipeline?

### ISSUE THREAD

**Issue by mattpilott** [mdarif/JavaScript-Boilerplate#12]
Hey mdarif,

Your boilerplate is really helpful and well written, is there any new updates or developments in the near future? Theres not much else on the internet that focuses on the best way to start a scalable js structure.

I just wondered if there was anything new or different that you might do now than you would have since your last commit.

Thanks,

**Comment by mdarif** [comment]
Thanks for the kind words @matt3224 , unfortunately I started towards next version of it but had to stop due to, not having enough time to work on it.

Anyhow, I would still recommend, if people do fork and send the pull requests to the open source project, without me, still it should work :)

**Comment by mattpilott** [comment]
That's a shame, I may fork the project and clean up some of the comments, perhaps extending it where I can.

**Comment by mdarif** [comment]
You still can do it, as I said, it's an open source project.
